### ISSUE TITLE
Migrate SPK to Bedrock CLI

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1068]
**As a:**
We want to move the `spk` tool to the Bedrock repository (this repository). The reason for this is to have the CLI tool live with the documentation about Bedrock.

### Copy SPK into gituhub.com/microsoft/bedrock
- [x] Model out the layout (Describe the new structure) #1073
- [x] Create list of changes in SPK and Bedrock respective repos to do before merge #1125
- [x] Merge the spk_docs branch of Bedrock to master branch of Bedrock #1114 
- [x] Move SPK repo to Bedrock-CLI and preserve history #1317 
- [x] Validate all guide links all work #1317 
- [x] Validate documentation generation works #1317 
- [x] Enable GitHub Pages on Bedrock repo #1317 
- [x] Validate build, release, smoke test pipelines working #1317 
- [x] Rename SPK #1354

### Having SPK in this repository may conflict with the Terraform modules and environments we have (will move to a new epic):

- Disable Terraform builds and/or make sure that SPK doesn't trigger them
- Move Terraform to another repo with build (optional)

**Comment by dennisseah** [comment]
Can git history be maintained after moved?

**Comment by andrebriggs** [comment]
> Can git history be maintained after moved?

Yes the `git subtree` command support this. See more [here](https://stackoverflow.com/a/47571452).
