### ISSUE TITLE
CLI should have specific error codes for every error

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1088]
Across `spk` we have inconsistent ways of handling exceptions. This epic proposes steps to normalize our approach to error handling and logging.

- [x] Produce a guideline doc on that covers how we should handle exceptions in SPK #1099
- [x] Have a look up file that contains error codes and their mean

---

- [x] commands: init #1310
- [x] error chain for `setup` command - https://github.com/microsoft/bedrock/issues/1294

---

- [x] error chain for deployment create command https://github.com/microsoft/bedrock/issues/1283
- [x] error chain for deployment dashboard command https://github.com/microsoft/bedrock/issues/1288
- [x] error chain for deployment get command - https://github.com/microsoft/bedrock/issues/1316
- [x] error chain for deployment onboard command - https://github.com/microsoft/bedrock/issues/1321
- [x] error chain for deployment validate command https://github.com/microsoft/bedrock/issues/1291

---
- [x] error chain for hld add variable group command - https://github.com/microsoft/bedrock/issues/1265
- [x] error chain for hld init command - https://github.com/microsoft/bedrock/issues/1284
- [x] error chain for hld reconcile command - https://github.com/microsoft/bedrock/issues/1293
- [x] error chain for hld install-manifest-pipeline command - https://github.com/microsoft/bedrock/issues/1323
---

- [x] error chain for `infra scaffold` and `infra generate` commands https://github.com/CatalystCode/spk/pull/446
---

- [x] error chain for project install-pipeline command https://github.com/microsoft/bedrock/issues/1257
- [x] error chain for project: create-variable-group, init commands #1307 
----

- [x] error chain for ring create, set-default, delete commands https://github.com/microsoft/bedrock/issues/1297

---
- [x] error chain for service create-revision commands #1308
- [x] error chain for service create commands #1339
- [x] error chain for service install-build-pipeline commands #1340

---
- [x] error chain for variable-group: create, command commands #1309

**Related Issues**
* `deployment get` fails silently if storage access key is wrong #1124

**Comment by dennisseah** [comment]
all sub tasks are completed
