### ISSUE TITLE
Dashboard needs caching support

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1090]
**As a:** developer

**I want:** some caching in the introspection tool

**So that:** I don't hit API limits for author queries

**Describe the solution you'd like:**
Right now even though most scenarios are using ADO, when using some GitHub configurations we are hitting the API limit for author queries. Since the commit Ids are not subject to change, it would be nice to cache the result for some of the deployments. 
- [x] Implement caching solution on backend #1264 
- [ ] Implement caching support in fronend #1318
- [x] Separate frontend and backend dependencies #1353 

**Acceptance Criteria:**
No longer hitting API limits.
We have a well structured repo
