### ISSUE TITLE
Merge the spk_docs branch of Bedrock to master branch of Bedrock

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1114]
**As a:**
Developer

**I want:**
 The spk_docs branch of Bedrock to be merged to master branch 

**So that:**
I'm not looking at two places for documentation and so that we don't have to hand point people to a branch for current documentation.  Finally, the automation is awesome and ready for hardy folks to try!

**Does this require updates to documentation?:**
YES

- [x] Rebase against master.
- [x] Review and revise documentation PR completely for one more pass.
- [ ] Merge infra docs PR #1030 (task #1038)
- [x] Merge gitops pipeline PR #1135
- [ ] Merge infra deep dive PR #1139 

**Acceptance Criteria:**
- [x] Able to run through all of the walkthroughs successful.
- [ ] All external links to current SPK repo work.
- [ ] All internal links to bedrock repo work against master.
