### ISSUE TITLE
Simplify inheritance of option values from config.yaml and improve op. doc.

### ISSUE THREAD

**Issue by dennisseah** [microsoft/bedrock#1289]
**As a:**
user

**I want:**
to know which options in the command inherit values from spk config.yaml

**So that:**
I do not need to provide values for these options

**Describe the solution you'd like:**
add information in the operational doc.

**Acceptance Criteria:**
inheritance information shows in operational doc.

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:**
no

design doc - https://github.com/CatalystCode/spk/blob/master/technical-docs/designs/commands/inheritFromConfigYaml.md

- [x] deployment create command - no actions needed
- [x] deployment dashboard command - no actions needed
- [x] deployment get command - no actions needed
- [x] deployment onboard command - https://github.com/microsoft/bedrock/issues/1290
- [x] hld append-variable-group command - no actions needed
- [x] hld init command - no actions needed
- [x] hld append-variable-group command - no actions needed
- [x] hld install-manifest-pipeline - https://github.com/microsoft/bedrock/issues/1306
- [x] hld reconcile command - no actions needed
- [x] infra generate command - no actions needed
- [x] infra scaffold command - no actions needed
- [x] project create-variable-group command - https://github.com/microsoft/bedrock/issues/1311
- [x] project init command - no actions needed
- [x] project install-lifecycle-pipeline command  - https://github.com/microsoft/bedrock/issues/1315
- [x] service create-revision command - https://github.com/microsoft/bedrock/issues/1312
- [x] service create command - no actions needed
- [x] service install-build-pipeline command - https://github.com/microsoft/bedrock/issues/1314

**Comment by dennisseah** [comment]
completed implementation for all commands
