### ISSUE TITLE
Spektate dashboard and pipeline scripts should support taking in additional data

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1429]
**As a:** developer

**I want:** to insert additional information to the azure storage table from pipelines

**So that:** I can capture information crucial to my project which the default bedrock-cli generated pipelines don't capture

**Describe the solution you'd like:**
Currently, our generated pipelines just capture the basic information that Spektate displays. Support needs to be added for the ability to capture additional data, add it to storage in a new column and display that information on Spektate. 
- [ ] Support additional arguments in `bedrock deployment create` command which captures data from pipelines
- [ ] Spektate package that fetches data from storage should gather all custom columns and return it in the response
- [ ] Spektate dashboard config (from https://github.com/microsoft/bedrock/issues/1428) should support adding additional column names that map to custom data in azure table.  
- [ ] Provide guidance through documentation to achieve this behavior

**Acceptance Criteria:**
Users are able to modify Spektate to fit their custom needs

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** Yes
