### ISSUE TITLE
Cluster/Infra Creation Epic

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#585]
## Spikes
- [Node pools w/availability zones](https://github.com/microsoft/bedrock/issues/417)

## Terraform work
- [Create a new Terraform environment template with the following:](https://github.com/microsoft/bedrock/issues/574)
  - Single AKS
  - Key Vault
  - Azure Monitor
  - Node pools w/availability zones 
  - ACR

## CLI Work

- [x] `spk infra validate` (and also `spk init`)
   - [x] [Validate prerequisites](https://github.com/microsoft/bedrock/issues/589) (e.g.terraform, az cli, helm, git)
   - [x] [Validate that user is logged in to Azure](https://github.com/microsoft/bedrock/issues/589)
   - [x] [Validate environment variables](https://github.com/microsoft/bedrock/issues/589) (e.g. ARM_SUBSCRIPTION_ID, ARM_CLIENT_ID, ARM_CLIENT_SECRET, and ARM_TENANT_ID) are set and not null
   - [x] [Create soft/hard checks for validation](https://github.com/microsoft/bedrock/issues/615)
   - [x] [Create a state file for initialization (in ~/.spk/spk-config.yaml)](https://github.com/microsoft/bedrock/issues/615)
      - [ ] [Write versions of executables to spk-config.yaml](https://github.com/microsoft/bedrock/issues/726)
- [ ] `spk infra scaffold --name <env name> --source <bedrock git url> --template <env template>` 
   - [ ] Validate that `spk infra validate` has run (check for existence of ~./spk/spk-config.yaml infra block)
   - [x] Clone official/custom Bedrock repo provided by the `--source` argument (potentially to a `tmp` directory)
      - [x] [Support for cloning private repos](https://github.com/microsoft/bedrock/issues/740)
   - [x] [Create a folder for new environment](https://github.com/microsoft/bedrock/issues/657) 
   - [x] [Create a `definition.yaml` file with parameters like environment name, template name, and variables from a `variables.tf`](https://github.com/microsoft/bedrock/issues/657)
   - [x] [Supports remote backend state as part of `definition.yaml`](https://github.com/microsoft/bedrock/issues/727) (if it exists)
- [ ] `spk infra generate --name <env name>`
   - [x] [Clone the source repo to fetch Terraform template](https://github.com/microsoft/bedrock/issues/653) (potentially to a `tmp` directory)
      - [x] [Support for cloning private repos](https://github.com/microsoft/bedrock/issues/740)
   - [x] [Create a "generated" directory](https://github.com/microsoft/bedrock/issues/653)
   - [x] [Copy Terraform template to the "generated" directory](https://github.com/microsoft/bedrock/issues/653)
   - [x] [Modify the Terraform template to use information provided by  the `definition.yaml` file](https://github.com/microsoft/bedrock/issues/653)
   - [x]  [Iterate through cluster directories](https://github.com/microsoft/bedrock/issues/721) (e.g. west, east), overwriting specific values in the cluster `terraform.tfvars` with values that are unique to the cluster `definition.yaml`
   - [x] [Backend State Support](https://github.com/microsoft/bedrock/issues/728)

Considerations:
- What happens if I move from machine A to machine B, where does the spk state live?
- What happens if the remote bedrock environment changes?
- What happens if I want to update a particular variable/etc?

**Comment by andrebriggs** [comment]
> Create a state file for initialization (in ~/.spk) 

Have we checked with the other groups about their need for cached data?

> Clone official/custom Bedrock repo using -p argument 

Are we requiring that a custom repo follows the same Bedrock directory structure?

>  Generates an infrastructure "HLD" (e.g. infra.json/yaml)

What exactly will be in here? 

CC @yradsmikham @NathanielRose

**Comment by NathanielRose** [comment]
@andrebriggs 

> Have we checked with the other groups about their need for cached data?
No we have not, will definitely surface if their is a need for other teams as well. Our thinking was targeting `spk infra init` then migrate to a `spk init` that calls other command initializations such as `spk project init` + `spk deployment init`
> Are we requiring that a custom repo follows the same Bedrock directory structure?
We are at the moment.  This can later be migrated to sparse cloning a repo based on a bedrock environment path to be passed to our `spk infra create`
> What exactly will be in here?
Our Brainstorm YAML:
``` yaml
---
Bedrock_Repo: True
Deployment_Name: Azure-ECK-Simple
Terraform_Version: 0.12.3
Bedrock_Source: (URL/LocalPath)
Data_Resources:[resource_group_name]
TFvars: 
{
resource_group_name      = "resource-group-name"
cluster_name             = "cluster-name"
agent_vm_count           = "3"
dns_prefix               = "dns-prefix"
service_principal_id     = "client-id"
service_principal_secret = "client-secret"
ssh_public_key           = "public-key"
gitops_ssh_url           = "git@github.com:timfpark/fabrikate-cloud-native-manifests.git"
gitops_ssh_key           = "<path to private gitops repo key>"
vnet_name                = "<vnet name>"
}
```

> CC @yradsmikham @NathanielRose

**Comment by yradsmikham** [comment]
@andrebriggs 

After reaching out to other teams, it appears that there could be a need to have some sort of "cached data". Service Introspection may need store keys, and Service Creation potentially may need to store spk logs or PATs. Regardless, there is a need (currently) for infra.

**Comment by NathanielRose** [comment]
@andrebriggs @yradsmikham Can this be closed?

**Comment by yradsmikham** [comment]
> @andrebriggs @yradsmikham Can this be closed?

Yes, it looks complete.
