### ISSUE TITLE
Service Creation Epic

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#586]
## Spikes
- [Spike to model a mono-repo](https://github.com/microsoft/bedrock/issues/578)
## CLI Work
- [x] [Use the CLI to initialize a mono-repo](https://github.com/microsoft/bedrock/issues/581)
  - [x] Create a Maintainers file
  - [x] Create a Bedrockconfig identifying the type of repository we're in (mono vs single), and the helm chart for the service.
- [x] [Use the CLI to create a new service in a mono-repo](https://github.com/microsoft/bedrock/issues/577)
  - [x] Create a directory for my service
  - [x] Create a maintainers file in this directory
  - [x] Create a gitignore in this directory
  - [x] Create a bedrockconfig in this directory
  - [x] Create azure pipelines yaml in this directory
  - [x] Commit and push the azure pipelines file (preferably to a new branch?)
  - [x] Create a new PR on behalf of this new service being added
- [x] [Use the CLI to create a service revision from an existing service](https://github.com/microsoft/bedrock/issues/579)
  - [x] Specify the initial branch/ring to deploy to in bedrockconfig (perhaps this is done as a consequence of initialization)
  - [x] Invoke a CLI command that would take in a branch name or use the present branch name to create a PR against the initial branch/ring - rebase against initial branch required
