### ISSUE TITLE
SPK introspection should support HLD PR information

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#652]
**As a:** developer/manager

**I want:** to see a column for PRs in the introspection tool

**So that:** I know which deployments are pending review, who approved past reviews etc.

**Describe the solution you'd like:**

Refer to this [Figma file](https://www.figma.com/file/LTcanBYtVdIg3IjyTxjQ8IP8/Ochestration-IA-Doc?node-id=332%3A1252) containing mock ups for how this should look like. 
- [x] Add support for PRs to the pipelines and storage table
- [x] Update the models to pull down this information and process it within the `Deployment.ts` class
- [x] Add necessary changes to backend and spektate package to support this change - https://github.com/microsoft/bedrock/issues/1165
- [x] Add this information as column(s) in the spk cli - https://github.com/microsoft/bedrock/issues/1167
- [x] Add this information as column(s) in the dashboard - https://github.com/microsoft/bedrock/issues/1166

**Comment by andrebriggs** [comment]
> Add support for PRs to the pipelines and storage table

@samiyaakhtar how would this work? Can you describe some high levels steps?

**Comment by samiyaakhtar** [comment]
@andrebriggs this was prioritized lower than other items because service creation was still in the process of adding support for PRs. There’s nothing stopping us.

**Comment by andrebriggs** [comment]
@samiyaakhtar I think we should de-prioritize this for the upcoming sprint

**Comment by samiyaakhtar** [comment]
@andrebriggs sounds good

**Comment by samiyaakhtar** [comment]
This task has a dependency on https://github.com/microsoft/bedrock/issues/978
