### ISSUE TITLE
[Epic][SPK] HLD Service Management Tracking

### ISSUE THREAD

**Issue by bnookala** [microsoft/bedrock#688]
**As a:**

Developer

**I want:**

To create services using SPK, and have them be synchronized to my HLD.

**So that:**

I can utilize my CLI tool to manage services in my bedrock service repositories and my HLD repository

**Describe the solution you'd like:**

An example using `spk`: 

`spk create service` _should_ add a service to the HLD repository by:
- [x] identify best method to operate HLD: #700 
- [x] call `spk hld reconcile` (#717 and #718) in a pipeline and open PR for HLD repository changes.
- [x] scaffold ingress routes for all rings within the service via #619

All of these tasks must be performed as a single unit and the artifacts committed as a Pull Request

**Describe alternatives you've considered:**

Instead of performing these operations via SPK, we can instead add a new pipeline to the repository that can perform these operations, leveraging fabrikate to take care of yaml modifications. 

**Additional context:**

Adding a new service requires modifications to the HLD.

**Does this require updates to documentation?:**

Yessirree

**Comment by mtarng** [comment]
Closing this epic out as all related tasks have been completed.
