### ISSUE TITLE
HCL file generating and parsing package

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#697]
**Topic:**
**HCL Files & SPK**

**Task**:  implement a minimal hcl/json object marshall/unmarshall module to support the requirements of the SPK command in particular `spk update` and `spk scaffold`.  Some work for writing out `hcl` has been done as mentioned below.

Prior work (under options) - discovery as well as implementation are mentioned.

*Options*
- Yvonne has taken an initial step to build an HCL generator. [PR83](https://github.com/CatalystCode/spk/pull/83)
- Also Identified a parser - https://github.com/hashicorp/hcl/tree/master/hcl/parser

Plan:

There are no applicable parsers currently for HCL.  What this task will do is to provide a mechanism for manually parsing and generation HCL files for supporting infra requirements.

HCL looks something like:

```
# Linode provider block. Installs Linode plugin.
provider "linode" {
    token = "${var.token}"
}

variable "region" {
  description = "This is the location where the Linode instance is deployed."
}

/* A multi
   line comment. */
resource "linode_instance" "example_linode" {
    image = "linode/ubuntu18.04"
    label = "example-linode"
    region = "${var.region}"
    type = "g6-standard-1"
    authorized_keys = [ "my-key" ]
    root_pass = "example-password"
}
```

Tasks:

- [ ] Implement HCL reader
- [ ] Implement HCL writer
- [ ] Package functionality as a library / module

Existing example / code:

- In the existing `infra/scaffold.ts` file there is an example from writing out a JSON object as HCL.  This example will be leveraged.

**Comment by jmspring** [comment]
Thinking - we will likely only be parsing the HCL that we generate/update, as such the parse should only handle our use cases (and expand as needed).

**Comment by yradsmikham** [comment]
> Thinking - we will likely only be parsing the HCL that we generate/update, as such the parse should only handle our use cases (and expand as needed).

@jmspring @NathanielRose but when would we need to parse an HCL file?

**Comment by jmspring** [comment]
Update will be one area for parsing.

**Comment by andrebriggs** [comment]
@jmspring @NathanielRose This is marked as extra small. How far into parsing and construct HCL are we going to go?

**Comment by jmspring** [comment]
> @jmspring @NathanielRose This is marked as extra small. How far into parsing and construct HCL are we going to go?

@andrebriggs - the minimal set of marshaling / unmarshaling for our use case will be done.  If you look at other HCL parsers (which this will not be in anyway a full one), there are points made that HCL itself is not definitively parsable in all situations.

If we run into a case that isn't supported in the future that becomes a bug/feature enhancement.

This work is specifically to support the initial implementation of `spk update`.

**Comment by yradsmikham** [comment]
pivoting away from Terragrunt. Closing issue.
