### ISSUE TITLE
[Design] - Terragrunt versioning target: Terraform source block or meta variable in extra_args?

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#698]
**Topic:**
**SPK versioning with Infra**

**Question:**
When out of box implementation `spk infra scaffold`, the command currently targets a template with `.tf` files and a declared `variable.tf` to scrape the variables and place them into an HCL file block for input. It also carries over the `.tf` files into the template folder. 

Alternatively, terragrunt allows a user to pass a template folder from a git URL as a source. It will then clone the folder into a terragrunt cache.

Where would we apply a version? If a version is applied from our current implementation of `spk infra scaffold` we will have no concept of a commit ID to use for a template version.  If a version is passed from a git source, we are requiring a repo for a starter project in which it will clone an empty project into a terragrunt cache.

Additionally, how would we automate updates to that version?

**[REQUIRED] Follow Up**
- [x] Using terragrunt is it possible to maintain `.tf` files for DRY leaves.
- [x] Versioning with Terragrunt implementation source vs using a tag
- [x] What does an update look like?

**Comment by andrebriggs** [comment]
@NathanielRose looks like you changed the sizing of this and updated the description. What the status here?

**Comment by NathanielRose** [comment]
- Design foundings have been placed here - https://github.com/NathanielRose/spk-terragrunt-tests/blob/master/SPK-Infra.md
- Reviewed on 11/24 meeting and have decided to build our own `spk` utility around generating and partial config - https://github.com/NathanielRose/spk-terragrunt-tests/blob/master/SPK-Infra.md
