### ISSUE TITLE
SPK introspection tool should visualize cluster and ring information

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#815]
**As a:** user of spk

**I want:** to visualize the two dimensional setup of my clusters and rings

**So that:** I can understand what versions of services are running on a particular ring in a particular cluster/environment.

**Describe the solution you'd like:**
The following pieces are a nice to have for the dashboard:
- Show some sort of indication that there are multiple cluster regions watching the same manifest repository
- Indicate the region names based on their flux sync tags, such as `flux-usa`, `flux-emea` and display the deployment running on these clusters on the dashboard, perhaps by showing multiple cluster sync indicators in a column (need some work with the designer)
- Brainstorm and come up with some user experiences that may be a good solution for fitting this within the current dashboard, or possibly consider adding a separate view to visualize this information.

An example of a service matrix formed by clusters and rings:

| Region/Ring     | (... custom rings) | Dev | QA | Prod |
| ---      | ---       | ---      | ---       | --- |
| USA | 0.1         | 0.2         | 0.1         | 0.1         | 
| Europe     | 0.1        | 0.2        | 0.2         | 0.1         |
| Africa     | 0.1        | 0.2        | 0.1         | 0.1         |

Related work: 
- [x] [Introspection tool should read multiple flux sync tags prefixed by `flux`](https://github.com/microsoft/bedrock/issues/814)
- [x] [Add git-sync-tag variable to terraform template for flux](https://github.com/microsoft/bedrock/issues/813)
- [x] [Introspection tool should display multiple cluster sync statuses in a separate column](https://github.com/microsoft/bedrock/issues/840)
- [ ] `spk deployment` commands should have support for cluster sync statuses #844

**Acceptance Criteria:**
A solution for cluster information along with rings

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** Yes

**Comment by andrebriggs** [comment]
@samiyaakhtar @edaena both of the listed tasks here are complete. Is this epic done? If not can we update the description and add links to new task? Thanks

**Comment by samiyaakhtar** [comment]
@andrebriggs added link to the remaining task

**Comment by andrebriggs** [comment]
> ... (to be expanded further)

@samiyaakhtar is there anything further that we need in the future or that has been requested?

**Comment by samiyaakhtar** [comment]
@andrebriggs not that i'm aware of, we'll have a discussion around the UI for this in the next sync with @gemorris
