### ISSUE TITLE
[SPK][Epic] Extend smoke tests to curl different rings

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#838]
**As a:**
Developer/Test runner

**I want:**
To be able to test my ring deployments via the smoke test.

- [ ] Requires #805 
- [ ] Requires infrastructure to be deployed/ or run via minicube or Kubernetes in docker (KinD) with an agent VM. 

The smoke test should:
- [ ] Create custom helm charts in the application repository
- [ ] Check that these charts are copied over into the HLD repository via the lifecycle pipeline.
- [ ] Add new ring to the project
- [ ] Check that the traefik ingress routes are created
- [ ] Curl the appropriate endpoint for that new ring/service combo with routing via Headers.

**So that:**
I can make sure code changes do not affect the logic.

**Acceptance Criteria:**

**Additional context:**

**Does this require updates to documentation?:**
Yes, mainly the test documentation

**Comment by andrebriggs** [comment]
@mtarng this is blocked right?
> Add new ring to the project

**Comment by mtarng** [comment]
@andrebriggs Correct. We'll need this work first: https://github.com/microsoft/bedrock/issues/955
