### ISSUE TITLE
Only rely on variable groups as opposed to baked in variables in yaml in SPK

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#839]
**As a:** Developer/ SPK User

**I want:** `spk project cvg` to add the created variable group into the
lifecycle pipeline definition for a given project.

**So that:** The pipeline can utilize the created variable group for secrets.

**Describe the solution you'd like:** The existing flow is currently:

- `spk project init` initializes the project repo, including
  `hld-lifecycle.yaml`
- `spk project install-lifecycle-pipeline` deploys the pipeline
- `spk project cvg` creates a variable group and adds the reference to
  `bedrock.yaml`

We would like to run `spk project cvg` prior to
`spk project install-lifecycle-pipeline` so that `spk project cvg` command
updates the `hld-lifecycle.yaml` with a newly created variable group name. When
user runs `spk project install-lifecycle-pipeline`, the pipeline will be
installed with correct variable group name.

- [x] [Project needs to run in order -- Each command should make sure it’s run in order. throw errors/info messages to user if not.](https://github.com/microsoft/bedrock/issues/886)
  - [x] init - can be run anytime -- existing functionality should be fine as it
        currently logs a warning that an existing `bedrock.yaml` file exists as
        performs a noop
  - [x] CVG - checks to see an existing `bedrock.yaml` file exists and adds the
        variable group to it; throws if it does not.
  - [ ] install-pipeline - checks to see that a `bedrock.yaml` file exists and
        that it has at least one variable group; throws if it does not
  - [x] [Remove flags for adding pipeline variables for project pipeline and service pipeline. We will only support using variable groups.](https://github.com/microsoft/bedrock/issues/886)
- [x] [Service pipelines should only use project Variable group](https://github.com/microsoft/bedrock/issues/887)
- [x] [modify the smoke tests to use the variable group created, instead of passing variables for `spk project install-lifecycle-pipeline` via flags.](https://github.com/microsoft/bedrock/issues/888)
  - [x] Smoke Test Additionally check behavior for HLD -> Manifest pipeline. I
        believe we’re using pipeline variables for this one, but I think that’s
        fine, since the HLD repo could live anywhere, and isn’t strictly aligned
        with a project.

**Acceptance Criteria:** running `spk project cvg` with a
`--lifecycle-pipeline-yaml` flag will update the pipeline definition with the
reference to the created variable group.

- running `spk project install-lifecycle-pipeline` will automatically inject
  created variable groups via `spk project cvg` into the created pipeline
- Errors are thrown if operations are run out of order

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** Yes!

**Comment by andrebriggs** [comment]
@mtarng if I'm understanding correct this reduces 3 spk calls to 2 spk calls?

**Comment by mtarng** [comment]
No, there would still be 3 calls @andrebriggs This just gives the "create variable group" command the option to modify the pipeline definition, either before or after installing the pipeline.

**Comment by evanlouie** [comment]
@andrebriggs note. After discussing with @sarath-p, @mtarng, and @bnookala, we've realized the preferred flow has blown up into something much larger (almost epic). We will have to break this down into smaller tasks.

**Comment by andrebriggs** [comment]
@evanlouie @sarath-p is the description reflective of the epic story? We can convert this

**Comment by evanlouie** [comment]
yup. This is now considered an Epic -- the top level tasks describe the issues that need to come out of it.

**Comment by andrebriggs** [comment]
> yup. This is now considered an Epic -- the top level tasks describe the issues that need to come out of it.

@evanlouie @sarath-p  Do we have a separate task to track the small parts? If so please link them

**Comment by andrebriggs** [comment]
We need to put a hold to this entire story until variable group issues are fixed @sarath-p @evanlouie @mtarng

**Comment by andrebriggs** [comment]
@sarath-p you have created a task that references this right?
>  install-pipeline - checks to see that a bedrock.yaml file exists and
that it has at least one variable group; throws if it does not

**Comment by sarath-p** [comment]
Currently, 2 out 3 pipelines enforces this validation. We still need to do #912 for manifest pipeline.
