### ISSUE TITLE
[SPK][EPIC] SPK Should be able to remove Services and Rings

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#858]
**As a:**
SPK User

**I want:**
To be able to remove rings and services via spk and pipelines

**So that:**
I don't have to manually remove them and worry about conflicts.

**Describe the solution you'd like:**
- [ ] As a user, if I remove a ring from a service, then the changes are reflected in: the associated `bedrock.yaml`, my `hld` repository, and the `materialized` repository.
- [ ] As a user, if I remove a service from my mono-repository, then the service should be removed from the associated `bedrock.yaml`, my `hld` repository, and the `materialized` repository.
- [ ] As a user, if I remove an external dependency (ie. Kafka, MongoDB) from my mono-repository, then:
  - [ ] then the external dependency should be removed from the associated `bedrock.yaml`, my `hld` repository, and the `materialized` repository, if and only if, it is not also being utilized by any other mono-repository linked to the same HLD and Materialized repositories.
- [ ] As a user, if I wish to delete a service repository or mono-repository, how would this be reflected in the downstream repositories? 

**Acceptance Criteria:**
If i have multiple bedrock application repositories (or even many mono-repositories) removing a shared referenced dependency from one, should not impact other repositories.

**Describe alternatives you've considered:**
Running `spk hld reconcile` locally/manually or through automation pipelines.

**Additional context:**
Previous work to add rings and services https://github.com/microsoft/bedrock/issues/717

**Does this require updates to documentation?:**
Yes!

**Comment by andrebriggs** [comment]
> **Describe the solution you'd like:**
> 
> * [ ]  As a user, if I remove a ring from a service, then the changes are reflected in: the associated `bedrock.yaml`, my `hld` repository, and the `materialized` repository.
> * [ ]  As a user, if I remove a service from my mono-repository, then the service should be removed from the associated `bedrock.yaml`, my `hld` repository, and the `materialized` repository.
> * [ ]  As a user, if I remove an external dependency (ie. Kafka, MongoDB) from my mono-repository, then:
>   
>   * [ ]  then the external dependency should be removed from the associated `bedrock.yaml`, my `hld` repository, and the `materialized` repository, if and only if, it is not also being utilized by any other mono-repository linked to the same HLD and Materialized repositories.
> * [ ]  As a user, if I wish to delete a service repository or mono-repository, how would this be reflected in the downstream repositories?

@evanlouie @bnookala @mtarng do we have sub tasks that correspond to these?

**Comment by evanlouie** [comment]
@andrebriggs Don't believe subtasks have been written yet. I think it would probably be best to wait for @bnookala and @mtarng to return to go through more thoroughly.

**Comment by andrebriggs** [comment]
@bnookala can you share you design doc here?

**Comment by bnookala** [comment]
![image](https://user-images.githubusercontent.com/87996/73100867-54b59880-3ea3-11ea-954b-37df8a2480c2.png)

![image](https://user-images.githubusercontent.com/87996/73100880-5b441000-3ea3-11ea-809d-e431487855f9.png)

**Comment by andrebriggs** [comment]
Non-indexable text in an image? 😅

**Comment by andrebriggs** [comment]
@bnookala @mtarng let's create a separate task for documenting how the user would use this and start that first
