### ISSUE TITLE
SPK methods need refactoring

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#885]
There is a a lot of code duplication in command methods. We can refactor SPK to reduce the amount of duplicated code, increase test coverage, and improve velocity.

1. move command declaration out of ts code. Using a json file will make code documentation easy to generate. Here is an example of generated docs https://gist.github.com/dennisseah/0e817cafee7b5101c7a61068e6cc48ef
2. having all command related file to have same structures
   A. have a commandDecorator function
   B. have a execute function
   C. call the same exit function
3. extensively reuse code by creating helper functions
4. have test coverage to be around 80-90%-ish
5. Make sure that we have promisify function right. That's not do not return promise unless it it needed.

there are 2 commands that questionable, hence small changes are made to these command

- [X] `spk  group-variable create` - there are plans to merge it with `spk  service create-group-variable`
- [X] `spk service create-revision` - related to rings

these are the targeted commands 
- [X] spk init
- [X] spk deployment create
- [X] spk deployment dashboard
- [X] spk deployment get
- [X] spk deployment onboard
- [X] spk deployment validate
- [X] spk hld init
- [X] spk hld install-manifest-pipeline
- [X] spk hld reconcile
- [X] spk infra generate
- [X] spk infra scaffold
- [X] spk infra validate
- [X] spk project create-variable-group 
- [X] spk project init
- [X] spk project install-lifecycle-pipeline
- [X] spk project init
- [X] spk service create
- [x] spk service install-build-pipeline

**Comment by yradsmikham** [comment]
This seems to be very broad and not quite scoped out. Should we list the refactoring items here for `spk infra`?
