### ISSUE TITLE
SPK Infra integration tests need more coverage

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#919]
**As a:**
Developer
**I want:**
Improved reliable integration testing for SPK Infra Generation Pipeline
**So that:**
I can ensure that my Generation pipeline will run smoothly in production.
**Describe the solution you'd like:**
Expand on the current `spk infra `integration tests in `infra-validations.sh` and `functions.sh` to incorporate the following:
- [x] [Creation of variable group with private values for sensitive tokens to use in generation pipeline](https://github.com/microsoft/bedrock/issues/965)
- [x] [Terraform Linting on terraform template prior to `spk infra scaffold` in generation pipeline](https://github.com/microsoft/bedrock/issues/970)
- [x] [Improved validation of Generated repo to account for `spk.tfvars` file content](https://github.com/microsoft/bedrock/issues/973)

**Acceptance Criteria:**
Updated  `infra-validations.sh` & `infra-generation-pipeline.yml`

**Additional context:**
Continuation of #872 

**Does this require updates to documentation?:**
No

**Comment by andrebriggs** [comment]
@NathanielRose to me I'm thinking this is a low priority because with the existing integration test and existing unit tests we should have a lot covered. What do you think?

**Comment by NathanielRose** [comment]
@andrebriggs agreed this can be labeled as low pri to allow us to focus on final documentation

**Comment by andrebriggs** [comment]
@NathanielRose I've turned this into a epic so we can break out your task list to small tasks. Which one do you think we should do first? Let's create a task for it

**Comment by NathanielRose** [comment]
> @NathanielRose I've turned this into an epic so we can break out your task list to small tasks. Which one do you think we should do first? Let's create a task for it

Sure thing, Private secrets in the VG will be a good start - https://github.com/microsoft/bedrock/issues/965

**Comment by NathanielRose** [comment]
Closed in #965 , #970 , and #973
