### ISSUE TITLE
Make Bedrock CLI `service create` topic more intuitive

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#943]
**As a:**
SPK user

**I want:**
To have 2 required arguments specifying my `serviceName` and `servicePath` when I create a service.

Rewrite `spk service create <service-name>` to be `spk service create <service-name> <path-to-service>

**So that:**
spk and all other consuming tools, repositories, and pipelines can reference my service in a much clearer way, avoiding any confusion between "mono-repositories" and "single-service repositories". 

**Describe the solution you'd like:**
- [ ] change service create command to: `.command("create <service-name> <service-path>")`
- [ ] Remove `--packages-dir` and `--display-name` from service `create`, and `install-build-pipeline`
- [ ] `IBedrockFile` should index services on serviceName:
```
export interface IBedrockFile {
  rings: {
    [branchName: string]: {
      isDefault?: boolean; // indicates the branch is a default branch to PR against when creating a service revision
    };
  };
  services: {
    [serviceName: string]: IBedrockServiceConfig;
  };
  variableGroups?: string[];
}
```
- [ ] IBedrockServiceConfig should contain a required reference to the servicePath:
```
export interface IBedrockServiceConfig {
  servicePath: string;
  middlewares?: string[];
  helm: IHelmConfig;
  disableRouteScaffold?: boolean;
  k8sBackendPort: number; // the service port for the k8s service Traefik2 IngressRoutes will point to
  pathPrefix?: string; // pathprefix for ingress route, ie. document-service
  pathPrefixMajorVersion?: string; // api version, will prefix path prefix if provided. ie. 'v1' will result in the endpoint: /v1/document-service
  k8sBackend?: string; // k8s service backend name for ingress routing
}
```
- [ ] Downstream commands that currently reference services by path are changed to reference by serviceName
- [ ] Documentation is updated to reflect these changes
- [ ] Smoketests are updated

**Additional context:**
Related Issues:
https://github.com/microsoft/bedrock/issues/1082 - `bedrock.yaml` should be versioned
https://github.com/microsoft/bedrock/issues/904 - `spk service create should ask for display name when path is "."`
https://github.com/microsoft/bedrock/issues/898 - `ingress routes do not use display name`
https://github.com/microsoft/bedrock/issues/908 - `Silent error related to Fabrikate in update_image_tag stage of SPK install-build-pipeline`
https://github.com/microsoft/bedrock/issues/907 - `Issues in `spk install-build-pipeline` produced azure-pipelines.yaml file`
https://github.com/microsoft/bedrock/issues/906 - `SPK install-build-pipeline issue around location of azure-pipelines.yaml file`
https://github.com/microsoft/bedrock/issues/1117 - Update `spk service create` and refactor bedrock.yaml

**Does this require updates to documentation?:**
Yes! This is major a breaking change for any existing Bedrock/SPK projects.

**Comment by andrebriggs** [comment]
@mtarng seems like something one person can handle  in a separate branch?

**Comment by mtarng** [comment]
Yes, I think we came to the consensus that this could all be done in a separate feature branch then merged back into master once thoroughly tested and reviewed.

**Comment by andrebriggs** [comment]
@mtarng What about the `spk service install-build-pipeline` command? Ar you proposing that command will be modified as well? cc #906

**Comment by mtarng** [comment]
@andrebriggs `spk service install-build-pipeline` will "look" the same as it is currently only accepting the <service-name> as an argument; however the current behavior is that the <service-name> accepted is actually the name of the directory. The proposed refactor means that the command will still look the same, but because we're indexing by the serviceName and because we have the path to where the service's directory actually is, we can remove the `--packages-dir` and `--display-name` flags

**Comment by andrebriggs** [comment]
@mtarng similar to my other suggestion let's create the documentation first as a task then implement what we have just written. Do you have an existing task for implement since this is an epic?

**Comment by mtarng** [comment]
This epic was closed via https://github.com/microsoft/bedrock/issues/1117
