### ISSUE TITLE
[SPK] Ring management (adding or removing rings)

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#955]
**As a:**
spk user
**I want:**
to be able to add or remove rings to my project via an spk cli command
**So that:**
I can manage my rings
**Describe the solution you'd like:**
- [ ] create a command to add a ring to a bedrock project: `spk ring create <ring-name>` or `spk ring add <ring-name>`. This command should:
  - Add the ring to the `bedrock.yaml` file.
  - For all existing services in this project, linked via the `bedrock.yaml` file, add the new ring to the build pipeline's branch trigger.

- [ ] create a command to remove a ring from a bedrock project: `spk ring remove <ring-name>` or `spk ring delete <ring-name>`. This command should:
  - Remove the ring from the `bedrock.yaml` file.
  - For all existing services in this project, linked via the `bedrock.yaml` file, remove the ring from the build pipeline's branch trigger.
  - This command will not allow the deletion of the default ring. Users must first change the default ring before deleting the current default ring.

- [ ] include a --git-push flag that will add all changes and open a PR against master.

- [ ] create a command to set the default ring: `spk ring set-default <ring-name>`. This command should set the default ring in the `bedrock.yaml` file.

- [ ] Extend smoke tests to add and remove rings.

**Comment by andrebriggs** [comment]
@mtarng first thing should be to create a task for documentation.

Do you have any other tasks to link to this epic?

**Comment by andrebriggs** [comment]
> Have a walkthrough guide that shows how and when a user would call spk ring create <ring-name>,spk ring set-default <ring-name>, and finally spk ring delete <ring-name>


@mtarng I added this to the task list
