### ISSUE TITLE
[Bedrock] Update Bedrock side rails to assure code environment stability and sustain version updates

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#964]
**As a:** Developer

**I want:** improved testing coverage on the bedrock repo

**So that:** The team can be assured of its sustainability during idle times of maintenance

**Describe the solution you'd like:** Improved handling and alerting of the Bedrock Repo to assure SPK team of required maintenance and mediation.

**Acceptance Criteria:**

- [ ] Code Coverage -- for Golang scripts used in terratest
- [ ] Observability and reporting
  - [ ] [Junit tests and reporting](https://github.com/microsoft/bedrock/issues/867)
  - [ ] Webhook alerting for failed integration tests in Master
  - [ ] Webhook alerting for failed custodian in Azure cleanup
- [ ] Update Integration Tests
  - [ ] Scheduled Integration Tests weekly
  - [ ] Decouple terraform commands from terratest 
- [ ] Bedrock V1

**Does this require updates to documentation?:** Yes

**Comment by NathanielRose** [comment]
- Unit Testing - Static Analysis - Linting, compliance, module verification, tflint, TF init / TF Plan
- Integration Testing - TF apply/ validate/ destroy (Parallel | Stages | Retries)
    - `tfoption.saveOption` between Tests
    - Add retry to integration tests
- End 2 End Testing (Optional) - Live dev environment and modify modules based on change.
