### ISSUE TITLE
Getting started with CLI needs to be easier for developers

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#986]
**Problem**: It is hard for people to get a working example of a gitops pipeline scaffolded by SPK in minutes

> `spk` needs some sort of wizard or interactive guide to deploy a working app, hld, and manifest repo with working pipelines

- [x] Have `spk setup` command https://github.com/CatalystCode/spk/pull/349
- [x] It will be interactive by default
- [x] Can accept a config file for non-interactively mode
- [ ] Create an end to end Bedrock environment for you, including
   - [x] AzDO project
   - [x] AzDO Repos
     - [x] HLD Repo #1086 
     - [x] Manifest Repos #1086
     - [x] Sample Application Repo #1113
   - [x] AzDO Pipelines
     - [x] HLD to Manifest Pipeline #1108
     - [x] Lifecycle Pipeline #11169
     - [x] Build Pipeline #1169
   - [x] Service Principal #1113
   - [x] Approving related pull requests #1169 
   - [x] Create storage account, table and partition key #1211 
   - [x] Auto approve HLD repo PRs #1337
 

 * Direct the user to a walk through guide to complete specific Bedrock scenarios  

Inspired by [spk-demo](https://github.com/andrebriggs/spk-demo)

**Comment by dennisseah** [comment]
@andrebriggs, can we close this?

**Comment by dennisseah** [comment]
removed "Setup should support visualstudio.com domains #1348". This is not planned for this epic. This shall be a nice to have enhancement.
